let component={ template: '<div class="main">啊啦，这个页面还没有完成或者通过测试，先去看一下其他功能吧</div>' };
const routers = [
    {
        path: '/',
        redirect: '/login'
    },
    {
        path:"/login",
        component:resolve=>require(['./views/login.vue'],resolve),
        meta:{
            title:"登录页面"
        }
    },
    {
        path:"/scan",
        component:resolve=>require(['./views/scanQR.vue'],resolve),
        meta:{
            title:"扫描二维码"
        }
    },
    {
        path:"/select",
        component:resolve=>require(['./views/select.vue'],resolve),
        meta:{
            title:"选择项目"
        }
    },
    {
        path:"/main",
        component:(resolve) => require(['./views/index.vue'], resolve),
        children:[
            {
                path:"project",
                component:(resolve)=>require(['./views/project.vue'],resolve)
            },
            {
                path:"issue/:type/:id",
                component:resolve=>require(['./views/flow.vue'],resolve),
                meta:{
                    title:"问题处理"
                }
            },
            {
                path:"all",
                component:resolve=>require(['./views/null.vue'],resolve),
                meta:{
                    title:"登录页面"
                },
                children:[
                    {
                        path:"project",
                        component:resolve=>require(['./views/all/event.vue'],resolve),
                        meta:{
                            title:"任务日程"
                        }
                    },
                    {
                        path:"modelView",
                        component:resolve=>require(['./views/all/modelView.vue'],resolve),
                        meta:{
                            title:"模型视图"
                        }
                    },
                ]
            },
            {
                path:'plan',
                component:(resolve)=>require(['./views/null.vue'],resolve),
                children:[
                    {
                        path:"constructionProgress",
                        component:(resolve)=>require(['./views/plan/constructionProgress.vue'],resolve),
                        meta:{
                            title:"施工进度"
                        }
                    },
                    {
                        path:"constructionPlan",
                        component:resolve=>require(['./views/plan/constructionPlan.vue'],resolve),
                        meta:{
                            title:"施工计划"
                        }
                    },
                    {
                        path:"constructionRecord",
                        component:(resolve)=>require(['./views/plan/constructionRecord.vue'],resolve),
                        meta:{
                            title:"进度录入"
                        }
                    }
                ]
            },
            {
                path:"quality",
                component:(resolve)=>require(['./views/null.vue'],resolve),
                children:[
                    {
                        path:"main",
                        component:(resolve)=>require(['./views/quality/main.vue'],resolve),
                        meta:{
                            title:"质量总览"
                        }
                    },
                    {
                        path:"add",
                        component:(resolve)=>require(['./views/quality/add.vue'],resolve),
                        meta:{
                            title:"发起整改单"
                        }
                    },
                    {
                        path:"deal",
                        component:(resolve)=>require(['./views/quality/overview.vue'],resolve),
                        meta:{
                            title:"处理整改单"
                        }
                    },
                    {
                        path:"check",
                        component:(resolve)=>require(['./views/quality/check.vue'],resolve),
                        meta:{
                            title:"质量验收"
                        }
                    },
                    {
                        path:"check/:id",
                        component:(resolve)=>require(['./views/quality/deal.vue'],resolve),
                        meta:{
                            title:"质量验收"
                        }
                    },
                    {
                        path:"spaceControl",
                        component:(resolve)=>require(['./views/quality/spaceControl.vue'],resolve),
                        meta:{
                            title:"空间管理"
                        }
                    },
                ]
            },
            {
                path:"safety",
                component:(resolve)=>require(['./views/null.vue'],resolve),
                children:[
                    {
                        path:"main",
                        component:resolve=>require(["./views/safety/main.vue"],resolve),
                        meta:{
                            title:"安全总览"
                        }
                    },
                    {
                        path:"add",
                        component:(resolve)=>require(['./views/safety/add.vue'],resolve),
                        meta:{
                            title:"发起整改单"
                        }
                    },
                    {
                        path:"deal",
                        component:(resolve)=>require(['./views/safety/overview.vue'],resolve),
                        meta:{
                            title:"处理整改单"
                        }
                    },
                ]
            },
            {
                path:"system",
                component:(resolve)=>require(['./views/null.vue'],resolve),
                children:[
                    {
                        path:"setting",
                        component:(resolve)=>require(['./views/system/setting.vue'],resolve),
                        meta:{
                            title:"系统设置"
                        }
                    },
                    {
                        path:"model",
                        component:resolve=>require(["./views/system/package.vue"],resolve),
                        meta:{
                            title:"模型管理"
                        }
                    }
                ]
            },
            {
                path:"file",
                component:resolve=>require(['./views/file.vue'],resolve),
                meta:{
                    title:"资料管理"
                }
            },

        ]
    },
    {
        path:"*",
        component:(resolve) => require(['./views/index.vue'], resolve),
    },
    {
        path:"/plannedQR",
        component:(resolve) => require(['./views/plannedQR.vue'], resolve),
    },
    {
        path:"/commonQR",
        component:(resolve) => require(['./views/commonQR.vue'], resolve),
    },
    {
        path:"/outlevel",
        component:(resolve) => require(['./views/outlevel.vue'],resolve),
        children:[
            {
                path:"strinfor",
                component:(resolve) => require(['./views/locator/strinfor.vue'],resolve),
            }
        ]
    },
    {
        path:"/modelss",
        component:(resolve) => require(['./views/building1.vue'], resolve),
    },
];
export default routers;